version: 2
jobs:
  build:
    working_directory: ~/pichincha-api
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: pichincha-api-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: pichincha-api-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/pichincha-api-reports
      - store_artifacts:
          path: target/pichincha-api-0.0.1-SNAPSHOT.jar