workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only:
                - develop

version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - pichincha-api-{{ checksum ".circleci/gcloud.sh" }}
      - run: /bin/bash .circleci/gcloud.sh
      - save_cache:
          paths:
            - ~/google-cloud-sdk
          key: pichincha-api-{{ checksum ".circleci/gcloud.sh" }}
      - run: mvn appengine:stage
      - persist_to_workspace:
          root: .
          paths:
            - target/pichincha-api

  deploy-test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - pichincha-api-{{ checksum ".circleci/gcloud.sh" }}
      - run: /bin/bash .circleci/gcloud.sh
      - attach_workspace:
          at: .
      - run: cd target/pichincha-api && ~/google-cloud-sdk/bin/gcloud app deploy

